TOPLEVEL_LANG = vhdl
TOPLEVEL = reg_file_mips
VHDL_SOURCES = ../src/reg_file_mips.vhd
MODULE = test_reg_file

SIM = ghdl
SIM_ARGS= --vcd=sim.vcd

include $(shell cocotb-config --makefiles)/Makefile.sim
